// Product image and video upload/serving, backed by R2.
//
// Uploaded files are untrusted. We never trust the browser's declared content type or the
// filename: the type is sniffed from the leading bytes, and the stored key is generated here
// so a crafted filename cannot traverse paths or collide with an existing object.

const MAX_BYTES = 5 * 1024 * 1024;
// Cloudflare's Workers request body limit varies by plan (100 MB on most paid plans) --
// this stays well under that so an upload fails with a clear message instead of a generic
// platform error. Raise it if your plan supports larger request bodies.
const MAX_VIDEO_BYTES = 50 * 1024 * 1024;

const SIGNATURES = [
  { type: 'image/jpeg', ext: 'jpg', bytes: [0xff, 0xd8, 0xff] },
  { type: 'image/png', ext: 'png', bytes: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] },
  { type: 'image/gif', ext: 'gif', bytes: [0x47, 0x49, 0x46, 0x38] },
];

// Sniffs the real image type from the file's leading bytes.
export function sniffImageType(buffer) {
  const view = new Uint8Array(buffer);

  for (const sig of SIGNATURES) {
    if (sig.bytes.every((b, i) => view[i] === b)) return sig;
  }

  // WEBP is "RIFF" + 4 size bytes + "WEBP".
  const ascii = (start, len) =>
    String.fromCharCode(...view.slice(start, start + len));
  if (view.length > 12 && ascii(0, 4) === 'RIFF' && ascii(8, 4) === 'WEBP') {
    return { type: 'image/webp', ext: 'webp' };
  }

  return null;
}

// MP4/MOV share the ISO base media container: a 4-byte box size, then the ASCII tag "ftyp"
// at byte 4. WebM is Matroska's EBML container, a fixed 4-byte magic number at byte 0.
export function sniffVideoType(buffer) {
  const view = new Uint8Array(buffer);
  if (view.length > 12) {
    const tag = String.fromCharCode(view[4], view[5], view[6], view[7]);
    if (tag === 'ftyp') return { type: 'video/mp4', ext: 'mp4' };
  }
  if (
    view.length > 4 &&
    view[0] === 0x1a &&
    view[1] === 0x45 &&
    view[2] === 0xdf &&
    view[3] === 0xa3
  ) {
    return { type: 'video/webm', ext: 'webm' };
  }
  return null;
}

function randomKey(ext) {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  const hex = [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('');
  return `${hex}.${ext}`;
}

// Two storage backends, because R2 needs a card on file and KV does not. R2 is preferred
// when it is bound (no per-object size ceiling worth worrying about, cheaper at volume);
// KV is the free fallback that covers product photos at a small shop's scale. Video only
// ever goes to R2 -- a KV value tops out at 25 MB.
export function imageStore(env) {
  if (env.IMAGES) return 'r2';
  if (env.IMAGES_KV) return 'kv';
  return null;
}

// Returns { ok, key, error }.
export async function storeImage(env, file) {
  const store = imageStore(env);
  if (!store) {
    return { ok: false, error: 'Image storage is not connected. Add the IMAGES_KV or IMAGES binding.' };
  }
  if (!file || typeof file.arrayBuffer !== 'function' || file.size === 0) {
    return { ok: false, error: 'No file was uploaded.' };
  }
  if (file.size > MAX_BYTES) {
    return { ok: false, error: `That file is ${(file.size / 1048576).toFixed(1)} MB. The limit is 5 MB.` };
  }

  const buffer = await file.arrayBuffer();
  const sig = sniffImageType(buffer);
  if (!sig) {
    return { ok: false, error: 'That is not a JPEG, PNG, WEBP or GIF image.' };
  }

  if (store === 'kv') {
    const key = randomKey(sig.ext);
    await env.IMAGES_KV.put(key, buffer, { metadata: { contentType: sig.type } });
    return { ok: true, key, contentType: sig.type };
  }

  const key = randomKey(sig.ext);
  await env.IMAGES.put(key, buffer, {
    httpMetadata: {
      contentType: sig.type,
      cacheControl: 'public, max-age=31536000, immutable',
    },
  });

  return { ok: true, key, contentType: sig.type };
}

// Returns { ok, key, error }. Same untrusted-file handling as storeImage, sized and sniffed
// for video instead.
export async function storeVideo(env, file) {
  if (!env.IMAGES) {
    return { ok: false, error: 'Video storage is not connected. Enable R2 and add the IMAGES binding.' };
  }
  if (!file || typeof file.arrayBuffer !== 'function' || file.size === 0) {
    return { ok: false, error: 'No file was uploaded.' };
  }
  if (file.size > MAX_VIDEO_BYTES) {
    return { ok: false, error: `That file is ${(file.size / 1048576).toFixed(1)} MB. The limit is ${MAX_VIDEO_BYTES / 1048576} MB.` };
  }

  const buffer = await file.arrayBuffer();
  const sig = sniffVideoType(buffer);
  if (!sig) {
    return { ok: false, error: 'That is not an MP4 or WEBM video.' };
  }

  const key = randomKey(sig.ext);
  await env.IMAGES.put(key, buffer, {
    httpMetadata: {
      contentType: sig.type,
      cacheControl: 'public, max-age=31536000, immutable',
    },
  });

  return { ok: true, key, contentType: sig.type };
}

// Keys are generated by us, so anything not matching the generated shape is a probe.
const KEY_PATTERN = /^[0-9a-f]{32}\.(jpg|png|webp|gif|mp4|webm)$/;

export async function serveImage(env, key) {
  if (!KEY_PATTERN.test(key)) return new Response('Not found', { status: 404 });

  const headers = new Headers();
  headers.set('cache-control', 'public, max-age=31536000, immutable');
  headers.set('x-content-type-options', 'nosniff');

  if (env.IMAGES) {
    const object = await env.IMAGES.get(key);
    if (object) {
      object.writeHttpMetadata(headers);
      headers.set('etag', object.httpEtag);
      return new Response(object.body, { headers });
    }
  }

  // Fall through to KV even when R2 is bound, so anything uploaded before R2 was turned on
  // keeps loading instead of 404ing the moment the better backend appears.
  if (env.IMAGES_KV) {
    const { value, metadata } = await env.IMAGES_KV.getWithMetadata(key, { type: 'arrayBuffer' });
    if (value) {
      headers.set('content-type', metadata?.contentType || 'application/octet-stream');
      return new Response(value, { headers });
    }
  }

  return new Response('Not found', { status: 404 });
}

export async function deleteImage(env, url) {
  const key = String(url || '').replace(/^\/img\//, '');
  if (!KEY_PATTERN.test(key)) return;
  if (env.IMAGES) await env.IMAGES.delete(key);
  if (env.IMAGES_KV) await env.IMAGES_KV.delete(key);
}

// A Google Drive "share" link points at a viewer page, not the file, so dropping one into
// an <img> renders a broken image. Rewrite it to Drive's direct-image endpoint instead.
//
// This is a stopgap for before R2 is connected, not a real hosting answer: Google rate-limits
// and sometimes blocks hotlinked Drive images, so a picture that works today can quietly stop
// loading later. Uploading to R2 is the fix.
export function normalizeImageUrl(url) {
  const raw = String(url || '').trim();
  if (!raw) return null;

  const drive =
    raw.match(/drive\.google\.com\/file\/d\/([\w-]+)/) ||
    raw.match(/drive\.google\.com\/open\?id=([\w-]+)/) ||
    raw.match(/drive\.google\.com\/uc\?(?:export=\w+&)?id=([\w-]+)/);
  if (drive) return `https://drive.google.com/thumbnail?id=${drive[1]}&sz=w1600`;

  return /^https:\/\//i.test(raw) ? raw : null;
}
