// Product image upload and serving, backed by R2.
//
// Uploaded files are untrusted. We never trust the browser's declared content type or the
// filename: the type is sniffed from the leading bytes, and the stored key is generated here
// so a crafted filename cannot traverse paths or collide with an existing object.

const MAX_BYTES = 5 * 1024 * 1024;

const SIGNATURES = [
  { type: 'image/jpeg', ext: 'jpg', bytes: [0xff, 0xd8, 0xff] },
  { type: 'image/png', ext: 'png', bytes: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] },
  { type: 'image/gif', ext: 'gif', bytes: [0x47, 0x49, 0x46, 0x38] },
];

// Sniffs the real image type from the file's leading bytes.
export function sniffImageType(buffer) {
  const view = new Uint8Array(buffer);

  for (const sig of SIGNATURES) {
    if (sig.bytes.every((b, i) => view[i] === b)) return sig;
  }

  // WEBP is "RIFF" + 4 size bytes + "WEBP".
  const ascii = (start, len) =>
    String.fromCharCode(...view.slice(start, start + len));
  if (view.length > 12 && ascii(0, 4) === 'RIFF' && ascii(8, 4) === 'WEBP') {
    return { type: 'image/webp', ext: 'webp' };
  }

  return null;
}

function randomKey(ext) {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  const hex = [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('');
  return `${hex}.${ext}`;
}

// Returns { ok, key, error }.
export async function storeImage(env, file) {
  if (!env.IMAGES) {
    return { ok: false, error: 'Image storage is not connected. Enable R2 and add the IMAGES binding.' };
  }
  if (!file || typeof file.arrayBuffer !== 'function' || file.size === 0) {
    return { ok: false, error: 'No file was uploaded.' };
  }
  if (file.size > MAX_BYTES) {
    return { ok: false, error: `That file is ${(file.size / 1048576).toFixed(1)} MB. The limit is 5 MB.` };
  }

  const buffer = await file.arrayBuffer();
  const sig = sniffImageType(buffer);
  if (!sig) {
    return { ok: false, error: 'That is not a JPEG, PNG, WEBP or GIF image.' };
  }

  const key = randomKey(sig.ext);
  await env.IMAGES.put(key, buffer, {
    httpMetadata: {
      contentType: sig.type,
      cacheControl: 'public, max-age=31536000, immutable',
    },
  });

  return { ok: true, key, contentType: sig.type };
}

// Keys are generated by us, so anything not matching the generated shape is a probe.
const KEY_PATTERN = /^[0-9a-f]{32}\.(jpg|png|webp|gif)$/;

export async function serveImage(env, key) {
  if (!env.IMAGES || !KEY_PATTERN.test(key)) {
    return new Response('Not found', { status: 404 });
  }

  const object = await env.IMAGES.get(key);
  if (!object) return new Response('Not found', { status: 404 });

  const headers = new Headers();
  object.writeHttpMetadata(headers);
  headers.set('etag', object.httpEtag);
  headers.set('cache-control', 'public, max-age=31536000, immutable');
  headers.set('x-content-type-options', 'nosniff');
  return new Response(object.body, { headers });
}

export async function deleteImage(env, url) {
  const key = String(url || '').replace(/^\/img\//, '');
  if (env.IMAGES && KEY_PATTERN.test(key)) {
    await env.IMAGES.delete(key);
  }
}
